version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot
      - run:
          name: Install yarn
          command: "curl -o- -L https://yarnpkg.com/install.sh | bash"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn make
      - run:
          name: Publish Builds
          command: ~/repo/node_modules/.bin/electron-forge publish
      - store_artifacts:
          path: ~/repo/out/make
